//@version=5
indicator("HullStragety", overlay=true)



// 參數定義


ATRShortStopLoss = input.source(close, title="ATR Short Stop Loss")
ATRLongStopLoss = input.source(close, title="ATR Long Stop Loss ")

MHULL = input.source(close, title="MHULL")
SHULL = input.source(close, title="SHULL")

var State = 0 //1 long sign 2 long trigger -1 short sign -2 short trigger
var SignPrice = 0.0

KallyEnable = input(bool(1), title="Kally Formula")
winRate = input(50.0, title="Win Rate")/100
WLRatio = input(1.5, title="Win/Loss Ratio take profit")
Kelly_Formula(winRate,profitRatio, winlossratio) =>
    f = winRate/winlossratio - (1-winRate)/profitRatio
    if(f<0)
        f:=0
    if(KallyEnable)
        f
    else
        1


BuySign = false
SellSign = false

HullBull = MHULL > SHULL
HullBear = MHULL < SHULL

HullBreakBull = low < MHULL and close<open
HullBreakBear = high > SHULL and close>open

switch (State)
    0 =>
        BuySign := false
        SellSign := false
        if (HullBear and HullBreakBear)
            State := 1
            SignPrice := high
        if (HullBull and HullBreakBull)
            State := -1
            SignPrice := low
    1 =>
        if (HullBear)
            if (close > SignPrice)
                State := 2
                BuySign := true
        if (HullBull)
            State := 0
        if (HullBull and HullBreakBull)
            State := -1
            SignPrice := low
                
    -1 =>
        if (HullBull)
            if (close < SignPrice)
                State := -2
                SellSign := true
        if (HullBear)
            State := 0
        if (HullBear and HullBreakBear)
            State := 1
            SignPrice := high
    2 =>
        if (HullBull and HullBreakBull)
            State := -1
            SignPrice := low
    -2 =>
        if (HullBear and HullBreakBear)
            State := 1
            SignPrice := high

plotshape(BuySign? ATRLongStopLoss:na, style=shape.labelup, location=location.absolute, size=size.normal, color=color.green, text="Buy",textcolor=color.white)
plotshape(SellSign? ATRShortStopLoss:na, style=shape.labeldown, location=location.absolute, size=size.normal, color=color.red, text="Sell",textcolor=color.white)
plot(State, color=color.red)






