//@version=5
strategy("MACD", overlay=true,  pyramiding=1, default_qty_type=strategy.percent_of_equity, default_qty_value=10,commission_value=0.05,initial_capital=1000)

startYear = input(2023, "Start Year")
startMonth = input(3, "Start Month")
startDay = input(15, "Start Day")//50
endYear = year(timenow)
endMonth = month(timenow)
endDay = dayofmonth(timenow)
startTime = timestamp(startYear, startMonth, startDay, 00, 00)
endTime = timestamp(endYear, endMonth, endDay, 23, 59)
timelock = input(bool(0) ,"Time lock")

// 判斷當前條是否在指定的時間範圍內
inDateRange = time >= startTime and time <= endTime or (not timelock) 

leverage = input(1, "Leverage")

MACD = input.source(close, title="MACD")
MACDsignal = input.source(close, title="MACDsignal")
MACD_Cross = input(close, title="MACD Cross")
MACD_Offset = input(2, title="MACD Offset")

longCondition = MACD[MACD_Offset]>MACDsignal[MACD_Offset] and not na(MACD_Cross[MACD_Offset])
closeLongCondition = MACD[MACD_Offset]<MACDsignal[MACD_Offset] and MACD[MACD_Offset]<0

shortCondition = MACD[MACD_Offset]<MACDsignal[MACD_Offset] and not na(MACD_Cross[MACD_Offset])
closeShortCondition = MACD[MACD_Offset]>MACDsignal[MACD_Offset] and MACD[MACD_Offset]>0

if(inDateRange)
    if(longCondition)
        strategy.close("Short")
        strategy.entry("Long", strategy.long, qty=leverage*strategy.equity/close)
    // if(closeLongCondition)
        // strategy.close("Long")
    if(shortCondition)
        strategy.close("Long")
        strategy.entry("Short", strategy.short, qty=leverage*strategy.equity/close)
    // if(closeShortCondition) 
        // strategy.close("Short")


