//@version=5
strategy("HullMobo", overlay=true,  pyramiding=1, default_qty_type=strategy.percent_of_equity,process_orders_on_close=true ,default_qty_value=10,commission_value=0.05,initial_capital=1000)

startYear = input(2023, "Start Year")
startMonth = input(3, "Start Month")
startDay = input(15, "Start Day")//50
endYear = year(timenow)
endMonth = month(timenow)
endDay = dayofmonth(timenow)
startTime = timestamp(startYear, startMonth, startDay, 00, 00)
endTime = timestamp(endYear, endMonth, endDay, 23, 59)
timelock = input(bool(0) ,"Time lock")

// 判斷當前條是否在指定的時間範圍內
inDateRange = time >= startTime and time <= endTime or (not timelock) 

MHULL = input.source(close, title="MHULL")
SHULL = input.source(close, title="SHULL")



MoboBuy = input.source(close, title="MoboBuy Arrow")
MoboSell = input.source(close, title="MoboSell Arrow")

QQELine = input.source(close, title="QQELine")
QQEUP = input.source(close, title="QQE UP")
QQEDOWN = input.source(close, title="QQE DOWN")



var takePrice = 0.0
var stopPrice = 0.0

var QQEState = 0

longcondition = not na(MoboBuy) and not (QQEState== 1) and not na(QQEUP) and close > MHULL
shortcondition = not na(MoboSell) and not(QQEState== -1) and not na(QQEDOWN) and close < SHULL


WLRatio = input(1.5, title="Win/Loss Ratio take profit")

if not na(QQEUP)
    QQEState := 1
if not na(QQEDOWN)
    QQEState := -1

if na(QQEUP) and na(QQEDOWN)
    QQEState := 0

if (inDateRange)
    if (longcondition)
        strategy.entry("Long", strategy.long)
        takePrice := close + (close - SHULL) * WLRatio
        stopPrice := SHULL
    if (shortcondition)
        strategy.entry("Short", strategy.short)
        takePrice := close - (MHULL - close) * WLRatio
        stopPrice := MHULL

if (strategy.position_size > 0)
    // stopPrice :=SHULL
    strategy.exit("Take Profit", "Long", limit=takePrice, qty_percent=50)
    strategy.exit("Stop Loss", "Long", stop=stopPrice)
    if(not na(QQEDOWN))
        strategy.close("Long")

if (strategy.position_size < 0)
    // stopPrice :=MHULL
    strategy.exit("Take Profit", "Short", limit=takePrice, qty_percent=50)
    strategy.exit("Stop Loss", "Short", stop=stopPrice)
    if(not na(QQEUP))
        strategy.close("Short")

