//@version=6
strategy("Taker", overlay=true, pyramiding=1, default_qty_type=strategy.percent_of_equity, process_orders_on_close=true, default_qty_value=10, commission_value=0.05, initial_capital=1000)

startYear = input(2023, "Start Year")
startMonth = input(3, "Start Month")
startDay = input(15, "Start Day")
endYear = year(timenow)
endMonth = month(timenow)
endDay = dayofmonth(timenow)
startTime = timestamp(startYear, startMonth, startDay, 00, 00)
endTime = timestamp(endYear, endMonth, endDay, 23, 59)
timelock = input(bool(0), "Time lock")

// 判斷當前條是否在指定的時間範圍內
inDateRange = time >= startTime and time <= endTime or (not timelock)

float MHULL = input.source(close, title="MHULL")
float SHULL = input.source(close, title="SHULL")
float SMDiff = MHULL - SHULL

perSentApha = input(1.0, title="persentApha")

BullM = SMDiff*perSentApha

leverage = input(1.0, title="Leverage")

// 獲取當前倉位
currentPositionSize = strategy.position_size

// 獲取當前可動用的資金
currentEquity = strategy.equity

// 獲取當前價格
currentPrice = close

// 計算倉位的市值
positionValue = currentPositionSize * currentPrice

// 計算總投資組合的價值
// 計算倉位比例
PositionSize = currentEquity * BullM / currentPrice 

deltaPositionSize = PositionSize - currentPositionSize

if (inDateRange)
    if (deltaPositionSize > 0)
        strategy.entry("Long", strategy.long, qty=deltaPositionSize*leverage)
    else if (deltaPositionSize < 0)
        strategy.entry("Short", strategy.short, qty=-deltaPositionSize*leverage)



// 結束前計算
plot(SMDiff, color=color.new(color.blue, 0), title="SMDiff")
plot(BullM, color=color.new(color.green, 0), title="BullM")
plot(positionValue , color=color.new(color.orange, 0), title="positionValue")
plot(currentEquity, color=color.new(color.gray, 0), title="currentEquity")
plot(currentPositionSize, color=color.new(color.red, 0), title="currentPositionSize")
plot(PositionSize, color=color.new(color.purple, 0), title="PositionSize")
plot(deltaPositionSize, color=color.new(color.yellow, 0), title="deltaPositionSize")
